server:
  port: 8213
spring:
  application:
    name: admin-server
  cloud:
    consul:
      host: 172.17.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-url: http://172.17.0.1:8213/actuator/health
        hostname: 172.17.0.1
